### ISSUE TITLE
Syntax highlighting breaks when returning a reference type

### ISSUE THREAD

**Issue by DaveDuck321** [antroseco/vscode-graphene#1]
![image](https://user-images.githubusercontent.com/30243291/210645088-d0f55bf4-092a-4c15-a5fc-1d523bf10b01.png)

This happens because the function definition end match is never satisfied.

I played around with it a bit and I got the following (completely unmaintainable) regex that strictly matches any valid named type:
```regex
[a-zA-Z]\w*\s*(?:<\s*(?R)\s*(,\s*(?R)\s*)*>\s*)?(?:\[\s*[&\d]\s*(?:,\s*\d\s*)*\s*\]\s*)*&*
```
Without recursion we can't be as strict but I think this is required for VSCode:
```regex
[a-zA-Z]\w*\s*(<.+>\s*)?(?:\[\s*[&\d]\s*(?:,\s*\d\s*)*\s*\]\s*)*&*
```
^Leaving the above here so no-one needs to work it out again.

Imo this specific problem is better fixed by a more permissive match on the function return type.

**Comment by antroseco** [comment]
Oh God, and that's just for a single type...

I was aware of the issue, and you're right: it looks like we need to be more permissive.
The way I've set things up, you get no syntax highlighting until you've finished typing a declaration, which is unacceptable. I'll rewrite all the regexes at some point to not rely on any "future" characters.

**Comment by antroseco** [comment]
There is a way to do recursion btw (not in the regex ofc, but see `include` in https://macromates.com/manual/en/language_grammars)
