### ISSUE TITLE
Higlight keywords like TODO in comments

### ISSUE THREAD

**Issue by antroseco** [antroseco/vscode-graphene#15]
This is what the Python grammar uses
```json
		"codetags": {
			"match": "(?:\\b(NOTE|XXX|HACK|FIXME|BUG|TODO)\\b)",
			"captures": {
				"1": {
					"name": "keyword.codetag.notation.python"
				}
			}
		},
```
I'd like something similar.

**Comment by DaveDuck321** [comment]
Might not be necessary :upside_down_face:. I'm already using [todo-tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) for this -- it already works with Graphene because we've got  c-style comments.

**Comment by antroseco** [comment]
Looks pretty cool actually, but it's so simple I'd rather support it natively

**Comment by antroseco** [comment]
Added in 8cff45c18d230ecd9550bc19d3d9a7a678ce48ba
