### ISSUE TITLE
Comments are not highlighted in the first line of a struct typedef

### ISSUE THREAD

**Issue by DaveDuck321** [antroseco/vscode-graphene#7]
![image](https://github.com/antroseco/vscode-graphene/assets/30243291/33ba7984-b294-43de-8fce-b2ac089c8985)

![image](https://github.com/antroseco/vscode-graphene/assets/30243291/2f6f3f67-fbf5-411e-935f-5cb42d8f0693)

![image](https://github.com/antroseco/vscode-graphene/assets/30243291/a1c364c7-bf71-40a2-b9f9-54b2c93850bb)

![image](https://github.com/antroseco/vscode-graphene/assets/30243291/355e6625-60b5-400f-bcdf-9704fae9e0e5)

**Comment by antroseco** [comment]
Similar to #4
